In [1]:
import torch

In [2]:
input_ids=torch.tensor([2,3,5,1])

In [4]:
vocab_size=6
output_dim=3

torch.manual_seed(123)
embedding_layer=torch.nn.Embedding(vocab_size,output_dim)

In [7]:
embedding_layer.weight

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)

In [18]:

embedding_layer(torch.arange(0,4))

tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481]], grad_fn=<EmbeddingBackward0>)

<div class="alert alert-block alert-info">
<b>Embedding:</b> 
<p>    
    This is an example of Embedding and its dimensions.
    We have a tensor that is embedded and check the shape
</p>
</div>

import torch
import torch.nn as nn



In [22]:
# Create embedding layer: vocab_size=5, embed_dim=4
embedding = nn.Embedding(5, 4)

# Input: indices of words (batch of 2 sentences, each 3 words long)
x = torch.tensor([
    [0, 1, 3],   # "I love dogs"
    [0, 2, 4]    # "I hate cats"
])



In [23]:
# Get embeddings
out = embedding(x)

print("Shape of output:", out.shape)

Shape of output: torch.Size([2, 3, 4])


In [24]:
embedding.weight

Parameter containing:
tensor([[-2.1338,  1.0524, -0.3885, -0.9343],
        [ 1.0533,  0.1388, -0.2044, -2.2685],
        [-0.9133, -0.4204,  1.3111, -0.2199],
        [ 0.1838,  0.2293,  0.6177, -0.2876],
        [ 0.8218,  0.1512,  0.1036, -2.1996]], requires_grad=True)

In [25]:
out

tensor([[[-2.1338,  1.0524, -0.3885, -0.9343],
         [ 1.0533,  0.1388, -0.2044, -2.2685],
         [ 0.1838,  0.2293,  0.6177, -0.2876]],

        [[-2.1338,  1.0524, -0.3885, -0.9343],
         [-0.9133, -0.4204,  1.3111, -0.2199],
         [ 0.8218,  0.1512,  0.1036, -2.1996]]], grad_fn=<EmbeddingBackward0>)


🔹 Output

x shape = (2, 3) → batch of 2 sentences, each length 3

out shape = (2, 3, 4)

👉 Explanation:

2 → number of sentences (batch size)

3 → number of words in each sentence

4 → embedding dimension

So every word index is replaced by a 4-dimensional vector.

✅ In short:
If input is (batch_size, seq_length), output of nn.Embedding is (batch_size, seq_length, embedding_dim).